let colors = ['pink', 'yellow', 'purple', 'blue'];
let sizes = [10, 24, 36];
let positions = [
    {id: 0, top: '20', left: '20'},
    {id: 1, top: '1/4', left: '1/4'},
    {id: 2, top: '1/4', left: '1/2'},
    {id: 3, top: '2/3', right:'1/3'},
    {id: 4, top: '1/4', right:'1/2'},
    {id: 5, top: '3/4', left: '2/3'},
    {id: 3, top: '2/4', right:'1/4'},
    {id: 4, top: '2/4', right:'1/2'},
    {id: 5, top: '3/4', left: '1/3'}
];

// left-1/2	left: 50%;
// left-1/3	left: 33.333333%;
// left-2/3	left: 66.666667%;
// left-1/4	left: 25%;
// left-2/4	left: 50%;
// left-3/4

export function generateRandomDot() {
    let randomScale = Math.floor(Math.random() * (3 - 1)) + 1;
    let randomDuration = Math.floor(Math.random() * (5 - 2)) + 2;
    let randomDelay = Math.floor(Math.random() * (6 - 1)) + 1;
    let randomColor = colors[Math.floor(Math.random()*colors.length)];
    let randomSize = sizes[Math.floor(Math.random()*sizes.length)];
    let randomPosition = positions[Math.floor(Math.random()*positions.length)];

    return {
        scale: randomScale,
        opacity: 0.5,
        duration: randomDuration,
        delay: randomDelay,
        position: randomPosition,
        color: randomColor,
        size: randomSize
    }
}

export function generateRandomAIPost() {  
    let emojis = ["🐕","🐾","🐩","🐶","🐕‍🦺","🦮"].sort( () => .5 - Math.random() );;
    let comments =  ["cool!!!", "This is amazing", "wow this looks great"];
    let userNames = ["bri_123", "sam_got_2", "jennie_smt", "dizzy_candy", "skol34", "hymy_jon"];
    let stories = [
        "This post was generated by AI. How cool is that !!!",
        "Emoji Meaning The cooked sausage of a hot dog in a sliced bun and drizzled with yellow mustard.",
        "The domestic dog is a domesticated descendant of the wolf. ",
        "The dog derived from an ancient, extinct wolf, and the modern grey wolf is the dog's nearest living relative. "
    ];

    return {
      likes: Math.floor(Math.random() * (1000 - 100)) + 100,
      userName: 'devGhostStories',
      story: stories[Math.floor(Math.random()*stories.length)],
      tags: ['ai', 'devghoststories', 'aistories'],
      emojis: emojis.sort( () => 0.5 - Math.random()),
      commentUserName: userNames[Math.floor(Math.random()*userNames.length)],
      comment: comments[Math.floor(Math.random()*comments.length)]
    };
}