import Layout from '../components/layout'
import List from '../components/list'

export default function Blog() {
    let items = [
      {category: 'TWITTER', title: 'DogeCoin to the moon', text: 'Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke.'},
      {category: 'MEDIUM', title: 'Next.js the next js framework', text: 'Next.js is an open-source React front-end development web framework created by Vercel that enables functionality such as server-side rendering.'},
      {category: 'MEDIUM', title: 'DogeCoin', text: 'Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke. Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke.Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke.'},
      {category: 'MEDIUM', title: 'DogeCoin', text: 'Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke.'},
      {category: 'MEDIUM', title: 'DogeCoin', text: 'Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke.'},
      {category: 'MEDIUM', title: 'DogeCoin', text: 'Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke.'},
      {category: 'MEDIUM', title: 'DogeCoin', text: 'Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke.'},
      {category: 'MEDIUM', title: 'DogeCoin', text: 'Dogecoin is a cryptocurrency created by software engineers Billy Markus and Jackson Palmer, who decided to create a payment system as a joke.'},
    ];
    return (
      <Layout home>
        <section class="text-gray-600 body-font max-w-7xl mx-auto">
            <div class="container px-5 py-24 mx-auto">
                <div class="flex flex-col w-full mt-10 mb-20">
                    <h2 class="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">POWERED BY AI</h2>
                    <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Top relevant generated articles</h1>
                    <p class="lg:w-2/3 leading-relaxed text-base">All of the content on this page was generated by an AI model. You can read more bout the model and the sources that it uses as data here. You can read more bout the model and the sources that it uses as data here. You can read more bout the model and the sources that it uses as data here.</p>
                </div>
                <List items={items} />
            </div>
        </section>
      </Layout>
    )
  }